services:
  - type: web
    name: myportfolio
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_NAME
        value: "Raushan Kumar | Portfolio"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "4000"
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_ENABLE
        value: "true"
      - key: MYSQL_ATTR_SSL_CA
        value: "/etc/ssl/certs/ca-certificates.crt"
      - key: RUN_MIGRATIONS
        value: "true"
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: file
